spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/doctor
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 465
    username: bcb8bb50e0713d
    password: b8389533f4af90
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB
      location: ${java.io.tmpdir}

app:
  upload:
    dir: ${user.home}/uploads/profile-pictures
  billing:
    dir: ${user.home}/appointment_bills
