spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/doctor
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 465
    username: 170b8642aed31f
    password: 5e7f8cb4f4fb97
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
